package io.aethibo.combatcoach.shared.achievement.domain.utils

import io.aethibo.combatcoach.shared.achievement.domain.model.Achievement
import io.aethibo.combatcoach.shared.achievement.domain.model.AchievementCategory

fun defaultAchievements(): List<Achievement> = listOf(
    Achievement(
        key = AchievementKeys.FIRST_WORKOUT,
        title = "First Blood",
        description = "Complete your first workout.",
        iconRes = "ic_achievement_first",
        category = AchievementCategory.MILESTONES,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.WORKOUTS_10,
        title = "Ten Down",
        description = "Complete 10 workouts total.",
        iconRes = "ic_achievement_ten",
        category = AchievementCategory.VOLUME,
        progressTarget = 10,
    ),
    Achievement(
        key = AchievementKeys.WORKOUTS_50,
        title = "Half Century",
        description = "Complete 50 workouts total.",
        iconRes = "ic_achievement_fifty",
        category = AchievementCategory.VOLUME,
        progressTarget = 50,
    ),
    Achievement(
        key = AchievementKeys.WORKOUTS_100,
        title = "Centurion",
        description = "Complete 100 workouts. Warrior.",
        iconRes = "ic_achievement_hundred",
        category = AchievementCategory.VOLUME,
        progressTarget = 100,
    ),
    Achievement(
        key = AchievementKeys.MINUTES_60,
        title = "One Hour In",
        description = "Train for 60 total minutes.",
        iconRes = "ic_achievement_clock",
        category = AchievementCategory.VOLUME,
        progressTarget = 60,
    ),
    Achievement(
        key = AchievementKeys.MINUTES_600,
        title = "Ten Hours",
        description = "Train for 600 total minutes.",
        iconRes = "ic_achievement_clock2",
        category = AchievementCategory.VOLUME,
        progressTarget = 600,
    ),
    Achievement(
        key = AchievementKeys.MINUTES_6000,
        title = "100 Hours",
        description = "Train for 6000 total minutes. Legend.",
        iconRes = "ic_achievement_legend",
        category = AchievementCategory.VOLUME,
        progressTarget = 6000,
    ),
    Achievement(
        key = AchievementKeys.CREATED_WORKOUT,
        title = "Architect",
        description = "Create your first custom workout.",
        iconRes = "ic_achievement_create",
        category = AchievementCategory.SKILLS,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.CREATED_COMBO,
        title = "Combo Artist",
        description = "Create your first custom combo.",
        iconRes = "ic_achievement_combo",
        category = AchievementCategory.SKILLS,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.WEEK_WARRIOR,
        title = "Week Warrior",
        description = "Train 5 times in a single week.",
        iconRes = "ic_achievement_week",
        category = AchievementCategory.CONSISTENCY,
        progressTarget = 5,
    ),
    Achievement(
        key = AchievementKeys.FIRST_PLAN,
        title = "Planner",
        description = "Create your first training plan.",
        iconRes = "ic_achievement_plan",
        category = AchievementCategory.SKILLS,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.PLAN_COMPLETE,
        title = "Finisher",
        description = "Complete all days of a training plan.",
        iconRes = "ic_achievement_finish",
        category = AchievementCategory.MILESTONES,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.RATED_WORKOUT,
        title = "Critic",
        description = "Rate a workout after completing it.",
        iconRes = "ic_achievement_star",
        category = AchievementCategory.SPECIAL,
        progressTarget = 1,
    ),
    Achievement(
        key = AchievementKeys.PERFECT_WEEK,
        title = "Perfect Week",
        description = "Train every day for 7 consecutive days.",
        iconRes = "ic_achievement_perfect",
        category = AchievementCategory.CONSISTENCY,
        progressTarget = 7,
    ),
)
